# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: beomju
has_binder: false
has_settings: false
kind: frontend
labextension_name: scheduler-jupyter-extension
project_short_description: A JupyterLab extension.
python_name: scheduler_jupyter_extension
repository: ''
test: false

