name: Build and Release Docker Image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t my-docker-image:$GITHUB_REF_NAME .

    - name: Save Docker image to tar
      run: |
        docker save my-docker-image:$GITHUB_REF_NAME -o my-docker-image.tar

    - name: Upload Docker image to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./my-docker-image.tar
        asset_name: my-docker-image.tar
        asset_content_type: application/x-tar
